<?php
/**
 * Created by Jacky.
 * User: Jacky
 * E-Mail: jacky@carocrm.com or jacky@youaddon.com
 * Date: 7/28/2015
 * Time: 1:49 PM
 * Project: carofw
 * File: ModelBase.php
 */

namespace Modules\Backend\Models;

use Phalcon\Mvc\Model;

class ModelBase extends Model
{
    public $list_view;
    public $detail_view;
    public $edit_view;
    public $menu;

    static public function slugify($text)
    {
        // replace non letter or digits by -
        $text = preg_replace('~[^\\pL\d]+~u', '-', $text);
        // trim
        $text = trim($text, '-');
        // transliterate
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        // lowercase
        $text = strtolower($text);
        // remove unwanted characters
        $text = preg_replace('~[^-\w]+~', '', $text);
        if (empty($text)) {
            return 'n-a';
        }
        return $text;
    }

    /**
     * Inserts or updates a model instance. Returning true on success or false otherwise.
     * <code>
     * //Creating a new robot
     * $robot = new Robots();
     * $robot->type = 'mechanical';
     * $robot->name = 'Astro Boy';
     * $robot->year = 1952;
     * $robot->save();
     * //Updating a robot name
     * $robot = Robots::findFirst("id=100");
     * $robot->name = "Biomass";
     * $robot->save();
     * </code>
     *
     * @param array $data
     * @param array $whiteList
     * @return boolean
     */
    public function save($data = null, $whiteList = null)
    {
        if (empty($this->created)) {
            $this->created = date('Y-m-d H:i:s');
        }

        if (empty($this->user_created_id)) {
            $this->user_created_id = 0;
        }

        if (empty($this->deleted)) {
            $this->deleted = 0;
        }

        if (empty($this->slug) && !empty($this->name)) {
            $this->slug = $this->slugify($this->name);
        }

        return parent::save($data, $whiteList); // TODO: Change the autogenerated stub
    }

    /**
     * render custom code in setting view model
     * user can user row value of current model
     * example:
     * {{ id }} or {{ name }}
     *
     * @param $custom_code
     * @return mixed
     */
    public function renderCustomCode($custom_code)
    {
        preg_match_all('/\{\{(.*)\}\}/U', $custom_code, $fields);
        $find = array();
        $replace = array();
        $i = 0;
        foreach ($fields[1] as $field) {
            $find[] = $fields[0][$i];
            $field = trim($field);
            $replace[] = !empty($this->$field) ? $this->$field : '';
            $i++;
        }
        return str_replace($find, $replace, $custom_code);
    }

}