<?php
 return array (
  'dashboard' => 
  array (
    0 => 'index',
    1 => 'list',
    2 => 'detail',
    3 => 'edit',
    4 => 'popup',
    5 => 'save_relate',
    6 => 'save',
    7 => 'delete',
    8 => 'upload',
  ),
  'errors' => 
  array (
    0 => 'show404',
    1 => 'show401',
    2 => 'show500',
    3 => 'list',
    4 => 'detail',
    5 => 'edit',
    6 => 'popup',
    7 => 'save_relate',
    8 => 'save',
    9 => 'delete',
    10 => 'upload',
  ),
  'index' => 
  array (
    0 => 'index',
    1 => 'list',
    2 => 'detail',
    3 => 'edit',
    4 => 'popup',
    5 => 'save_relate',
    6 => 'save',
    7 => 'delete',
    8 => 'upload',
  ),
  'settings' => 
  array (
    0 => 'index',
    1 => 'repair',
    2 => 'rebuild_resources',
    3 => 'list',
    4 => 'detail',
    5 => 'edit',
    6 => 'popup',
    7 => 'save_relate',
    8 => 'save',
    9 => 'delete',
    10 => 'upload',
  ),
  'users' => 
  array (
    0 => 'index',
    1 => 'groups',
    2 => 'detail_group',
    3 => 'edit_group',
    4 => 'roles',
    5 => 'detail_role',
    6 => 'edit_role',
    7 => 'set_permissions',
    8 => 'list',
    9 => 'detail',
    10 => 'edit',
    11 => 'popup',
    12 => 'save_relate',
    13 => 'save',
    14 => 'delete',
    15 => 'upload',
  ),
);
