<?php
 return array (
  'builder' => 
  array (
    0 => 'index',
    1 => 'edit_model',
    2 => 'ajax_add_field',
    3 => 'ajax_add_index',
    4 => 'update_fields',
    5 => 'create_model',
    6 => 'edit_layout',
    7 => 'list',
    8 => 'detail',
    9 => 'edit',
    10 => 'popup',
    11 => 'save_relate',
    12 => 'save',
    13 => 'delete',
    14 => 'upload',
  ),
  'dashboard' => 
  array (
    0 => 'index',
    1 => 'list',
    2 => 'detail',
    3 => 'edit',
    4 => 'popup',
    5 => 'save_relate',
    6 => 'save',
    7 => 'delete',
    8 => 'upload',
  ),
  'errors' => 
  array (
    0 => 'show404',
    1 => 'show401',
    2 => 'show500',
  ),
  'index' => 
  array (
    0 => 'index',
    1 => 'logout',
    2 => 'list',
    3 => 'detail',
    4 => 'edit',
    5 => 'popup',
    6 => 'save_relate',
    7 => 'save',
    8 => 'delete',
    9 => 'upload',
  ),
  'menus' => 
  array (
    0 => 'index',
    1 => 'list',
    2 => 'refresh',
    3 => 'detail',
    4 => 'edit',
    5 => 'popup',
    6 => 'save_relate',
    7 => 'save',
    8 => 'delete',
    9 => 'upload',
  ),
  'rest' => 
  array (
    0 => 'execute',
  ),
  'settings' => 
  array (
    0 => 'index',
    1 => 'repair',
    2 => 'rebuild_resources',
    3 => 'mail_config',
    4 => 'list',
    5 => 'detail',
    6 => 'edit',
    7 => 'popup',
    8 => 'save_relate',
    9 => 'save',
    10 => 'delete',
    11 => 'upload',
  ),
  'users' => 
  array (
    0 => 'index',
    1 => 'groups',
    2 => 'detail_group',
    3 => 'edit_group',
    4 => 'roles',
    5 => 'register_roles',
    6 => 'detail_role',
    7 => 'edit_role',
    8 => 'set_permissions',
    9 => 'list',
    10 => 'detail',
    11 => 'edit',
    12 => 'popup',
    13 => 'save_relate',
    14 => 'save',
    15 => 'delete',
    16 => 'upload',
  ),
);
