<?php
/**
 * Created by Caro Team (info@carocrm.com).
 * User: Jacky (jacky@carocrm.com).
 * Year: 2016
 * File: MenusController.php
 */

namespace Modules\Backend\Controllers;


class MenusController extends ControllerCustom
{
    protected $model_name = 'Menus';

    public function indexAction()
    {
        $this->listAction();
    }
    
    public function listAction()
    {
        $this->view->extra_view_menus = array(
            array(
                'url' => '/menus/refresh',
                'label' => 'Refresh'
            )
        );
        
        parent::listAction(); // TODO: Change the autogenerated stub
    }

    public function refreshAction()
    {
        $this->view->disable();
        unlink(APP_PATH . 'apps/backend/permissions/menus.php');
        return $this->backendRedirect('/menus');
    }
}